### ISSUE TITLE
Reporter config improvement

### ISSUE THREAD

**Issue by thorgrin** [CESNET/liberouter-gui#37]
Mám problém s čitelností Nemea Reporter Configuration GUI. Pro následující příklad:
```
custom_actions:
  - id: store_mongo
    mongo:
       host: localhost
       db: nemeadb
       collection: alerts_new
  - id: store_warden
    warden:
      url: https://localhost/warden/
  - id: file
    file:
       path: /dev/stdout
  - id: sendmail
    email:
      to: root@localhost
      subject: "Example report"
      from: "nemead@localhost"
rules:
- id: 1
  condition: True
  actions:
  - store_mongo
  - store_warden
```
Dostanu:
<img width="803" alt="reporter_confg" src="https://user-images.githubusercontent.com/1065918/31946857-3ea3ec70-b8d3-11e7-9200-6092f448b86d.png">

Problémů je několik:
* není poznat, jaké akce se pro pravidlo volají
* u sendmail není políčko from
* u file jsou tlačítka Directory a File, nezjistil jsem, co dělají
* nejsou vidět ID pravidel, přestože id akcí vidět je. Toto je možná schválně?

Máme i trochu složitější konfigurace a tam je nepřítomnost popisků u akcí ještě větší problém. Zatím se většinou soubory vytvářejí ručně, nicméně bych rád přešel na aktivní používání GUI.

Btw, nejsem si jist, k čemu je položka url u wardenu, předpokládám, že se nepoužívá, je to tak? Pak ji z example odtraním...
